version: "3.8"
services:
  nodeapp:
    restart: unless-stopped
    build: .
    ##    Uncomment this if you want to expose app too.
    ##    ports:
    ##    - 3000:3000
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - nodeapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
